[project]
name = "mcp-b2c-oauth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "mcp[cli]>=1.9.4",
    "pydantic>=2.11.7",
    "pyjwt>=2.10.1",
]
